version: "3.7"
services:

  eccontes:
    image: csek06/appdynamics-server-all-in-one
    container_name: appd_eccontes
    hostname: eccontes
    ports:
      - "8090:8090"
      - "8181:8181"
      - "9080:9080"
      - "9081:9081"
      - "9191:9191"
    env_file:
      - your-platform.env
    environment:
      - SCENARIO=ECCONTES
      - COMPOSED=true
      - CONTROLLER_HOST=eccontes
      - DOCKER_HOST=$HOSTNAME
    volumes:
      - /opt/appdynamics:/opt/appdynamics
  
  eum:
    image: csek06/appdynamics-server-all-in-one
    container_name: appd_eum
    hostname: eum
    ports:
      - "7001:7001"
      - "7002:7002"
    depends_on:
      - eccontes
    env_file:
      - your-platform.env
    environment:
      - SCENARIO=EUM
      - COMPOSED=true
      - CONTROLLER_HOST=eccontes
      - EUM_HOST=eum
      - EVENTS_SERVICE_HOST=eccontes
      - EUM_SIZE=split
      - DOCKER_HOST=$HOSTNAME
    links:
      - eccontes
    volumes:
      - /opt/appdynamics:/opt/appdynamics
    restart: on-failure
    
  syntheticserver:
    image: csek06/appdynamics-server-all-in-one
    container_name: appd_syn_server
    hostname: syntheticserver
    ports:
      - "10101:10101"
      - "10102:10102"
      - "10001:10001"
      - "10002:10002"
    depends_on:
      - eccontes
      - eum
    env_file:
      - your-platform.env
    environment:
      - SCENARIO=SYN
      - COMPOSED=true
      - CONTROLLER_HOST=eccontes
      - EUM_HOST=eum
      - DOCKER_HOST=$HOSTNAME
    links:
      - eccontes
      - eum
    volumes:
      - /opt/appdynamics:/opt/appdynamics
    restart: on-failure
      
  databaseagent:
    image: csek06/appdynamics-server-all-in-one
    container_name: appd_db_agent
    hostname: databaseagent
    depends_on:
      - eccontes
    env_file:
      - your-platform.env
    environment:
      - SCENARIO=DA
      - COMPOSED=true
      - CONTROLLER_HOST=eccontes
      - DB_AGENT_NAME=$HOSTNAME
      - DOCKER_HOST=$HOSTNAME
    links:
      - eccontes
    volumes:
      - /opt/appdynamics:/opt/appdynamics
    restart: on-failure
    
  machineagent:
    image: csek06/appdynamics-server-all-in-one
    container_name: appd_ma_agent
    hostname: machineagent
    depends_on:
      - eccontes
    ports:
      - "9090:9090"
      - "9091:9091"
    env_file:
      - your-platform.env
    environment:
      - SCENARIO=MAAA
      - COMPOSED=true
      - CONTROLLER_HOST=eccontes
      - EVENTS_SERVICE_HOST=eccontes
      - MA_AGENT_NAME=$HOSTNAME
      - DOCKER_HOST=$HOSTNAME
    links:
      - eccontes
    volumes:
      - /opt/appdynamics:/opt/appdynamics
    restart: on-failure